### 1. 로그인 API 호출
POST {{host}}/v1/auth/sign-in
Content-Type: application/json

{
  "email": "tester@test.com",
  "password": "12345678"
}

> {% client.global.set("accessToken", response.body.data.accessToken); %}

### 2. 장바구니 항목 1건 추가
POST {{host}}/v1/cart-items
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "productId": 6122529005506560,
  "productName": "나이키 티셔츠",
  "selectedOptions": "색상_COLOR_BLACK/상의 사이즈_SIZE_M",
  "price": 1000,
  "quantity": 1,
  "amount": 1000,
  "discountedAmount": 0,
  "paymentAmount": 1000
}
