### 장바구니 항목 1건 추가
POST {{host}}/v1/cart-items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXJAdGVzdC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6NjEyMjM3ODU1NTgyMjA4MCwiZXhwIjoxNzQ3NDcyMjIzfQ.Eg2Jji7MdWIxPzdEHct5g6DqOHVNsgiZcEqeZ1_TUmo

{
  "productId": 6122529005506560,
  "productName": "나이키 티셔츠",
  "selectedOptions": "색상_COLOR_BLACK/상의 사이즈_SIZE_M",
  "price": 1000,
  "quantity": 1,
  "amount": 1000,
  "discountedAmount": 0,
  "paymentAmount": 1000
}
