### 1. 로그인 API 호출
POST {{host}}/v1/auth/sign-in
Content-Type: application/json

{
  "email": "tester@test.com",
  "password": "12345678"
}

> {%
    const token = response.body.data.grantType + ' ' + response.body.data.accessToken;
    client.global.set("accessToken", token);
%}

### 2. 장바구니 항목 1건 변경
PUT {{host}}0/v1/cart-items/6100402814586880
Content-Type: application/json
Authorization: {{accessToken}}

{
  "productId": 6122529005506560,
  "price": 1000,
  "quantity": 3,
  "amount": 3000,
  "discountedAmount": 0,
  "paymentAmount": 3000
}
