server.port: 8080

spring:
  profiles:
    active: local
  application:
    name: core-api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# 기본적으로 P6Spy 비활성화
decorator:
  datasource:
    enabled: false
