spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:mysql:8.0:///green
    username: green_user
    password: 123456

  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: 127.0.0.1:9092

jwt:
  access_secret: 256ff6d883fa12e4e426ee47d1eed5928bf4e03c8511ed7286804df5718b906d173b375d8b6521e4afddd0c540de311b8fe5ee73352f31a82eeb92c792bdcf66

app:
  node-id: 1
