CREATE TABLE IF NOT EXISTS USER (
    USER_ID BIGINT NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    IMAGE_URL VARCHAR(255),
    ROLES VARCHAR(100),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    PRIMARY KEY (USER_ID)
) ENGINE=INNODB;

-- 인덱스 생성
CREATE INDEX IDX__USER__PHONE ON USER(PHONE);
