version: '3'

services:
  mysql:
    container_name: master_mysql
    image: mysql:8.4.5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: green
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Seoul
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/docker-entrypoint-initdb.d
  redis:
    container_name: master_redis
    image: redis:7.4.3
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /conf/redis.conf
  kafka_broker:
    image: apache/kafka:3.8.0
    hostname: kafka_broker
    container_name: kafka_broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_broker:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka_broker:29092,CONTROLLER://kafka_broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    restart: always
