spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PROD_RDB_URL}
    username: ${PROD_RDB_USERNAME}
    password: ${PROD_RDB_PASSWORD}

  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate.default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: ${PROD_KAFKA_BOOTSTRAP_SERVERS}
