### 1. 상품 리스트 조회 (필수 옵션 포함)
GET {{host}}/v1/products?categoryPath=1&size=10&page=1

### 2. 상품 리스트 조회 (필수 + 선택 옵션 포함)
GET {{host}}/v1/products?categoryPath=1&size=10&page=1&colors=BLACK,WHITE&sizes=M&priceRange=100~50000&isInStock=true

### 3. 상품 리스트 조회 (필수 + 선택 옵션 포함)
GET {{host}}/v1/products?categoryPath=1&size=10&page=1&colors=BLACK&sizes=M

### 4. 상품 리스트 조회 (필수 + 선택 옵션 포함)
GET {{host}}/v1/products?categoryPath=1&size=10&page=1&colors=BLACK&sizes=L
