### 장바구니 항목 1건 추가
POST http://localhost:8080/v1/cart-items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXJAdGVzdC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6NTcxMTE5MzE4ODYwMTg1NiwiZXhwIjoxNzQ3NDYzOTE2fQ.GqcSxyWTNsW1NKvVK5Ir8YzLc_TgpLcsWY90qTcqm8o

{
  "productId": 1,
  "productName": "나이키 티셔츠",
  "selectedOptions": "색상_COLOR_BLACK/상의 사이즈_SIZE_M",
  "price": 1000,
  "quantity": 1,
  "amount": 1000,
  "discountedAmount": 0,
  "paymentAmount": 1000
}
