### 장바구니 항목 리스트 조회
GET http://localhost:8080/v1/cart-items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXJAdGVzdC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJJZCI6NTcxMTE5MzE4ODYwMTg1NiwiZXhwIjoxNzQ3NDYzOTE2fQ.GqcSxyWTNsW1NKvVK5Ir8YzLc_TgpLcsWY90qTcqm8o
