name: Green Backend Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      # 해당 저장소의 코드를 가져온다.
      - name: Checkout
        uses: actions/checkout@v4

      # Java 21를 사용한다.
      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      # Gradle wrapper 파일 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle test 실행
      - name: Test with Gradle
        run: ./gradlew --info test

      # 테스트 후 Result 출력
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml

      # 캐시 파일 삭제
      - name: Cleanup Gradle Cache
        if: always()
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties